### ISSUE TITLE
GID 998 will be unusable in rhel7.2

### ISSUE THREAD

**Issue by sdodson** [sclorg/mongodb-container#109]
Per https://github.com/openshift/mongodb/blob/master/2.4/Dockerfile.rhel7#L28-L32 mongodb user must always be uid=184 and gid=998   however in rhel7.2 images gid 998 is already in use by systemd packages.

```
docker run ${INTERNAL_REGISTRY}/rhel7.2 cat /etc/group | grep 998
systemd-bus-proxy:x:998:
```

When installing on rhel7.2 mongodb is uid=184 gid=995
So what to do? 

@jhadvig as you wrote the comment referenced above

**Comment by bparees** [comment]
I'm dubious that restriction is still necessary, we can probably remove it.

**Comment by sdodson** [comment]
Wouldn't you run into problems with ownership on persistent volumes if a
pod were restarted on a different node which had different version of the
image? I guess as long you change ownership on startup you'd be fine.

**Comment by mtrmac** [comment]
If you are going to change anything about UID/GID allocation, _please_ read https://fedoraproject.org/wiki/Packaging:UsersAndGroups and make sure whatever you decide to do is compatible with it, and with the implicitly used values from `grep '[UG]ID_' /etc/login.defs`. Hard-coding 998 should never have happened.

**Comment by bparees** [comment]
@mnagy @rhcarvalho I think one of you were the original reason we were doing this in the postgres or mysql image, can you refresh my memory on why we're doing this check and confirm it's really still needed now that we run as any user anyway?

**Comment by rhcarvalho** [comment]
> I guess as long you change ownership on startup you'd be fine.

From my experience working on this, OpenShift doesn't change ownership of files and directories when mounting the persistent volume. But honestly I don't know the code bits related to mounting PVs and my observation could be wrong.

@bparees I never fully grasped why this was needed, its existence predates me in the project :)
I'm +1 for trying to remove it.

**Comment by mnagy** [comment]
Yeah, we can remove it. Will do.
