### ISSUE TITLE
Make test failures reporting better

### ISSUE THREAD

**Issue by mfojtik** [sclorg/mongodb-container#15]
@jhadvig when Jenkins fails, it is impossible to parse the Jenkins console output by my poor brain. Can you please print out the test case name and mark the failure using bold color or at least three exclamation marks :-)

**Comment by bparees** [comment]
@mfojtik, I don't think we can hope for @jhadvig to do this anymore :)

**Comment by jhadvig** [comment]
@bparees :+1: 
@mfojtik enjoy ;)

**Comment by mfojtik** [comment]
@bparees I do believe this is now better, but will see when mongodb explode in Jenkins :-)

**Comment by hhorak** [comment]
mongodb container is not maintained any more in this org. closing.
