### ISSUE TITLE
Not possible to do port-forward to mongo32

### ISSUE THREAD

**Issue by jorgemoralespou** [sclorg/mongodb-container#172]
There is no socat in the image and port-wordfarding fails:

```
$oc port-forward mongodb-1-zusc8 27017:27017
I0811 13:31:54.234934   35913 portforward.go:213] Forwarding from 127.0.0.1:27017 -> 27017
I0811 13:31:54.235037   35913 portforward.go:213] Forwarding from [::1]:27017 -> 27017
I0811 13:32:01.249564   35913 portforward.go:247] Handling connection for 27017
E0811 13:32:01.260688   35913 portforward.go:318] an error occurred forwarding 27017 -> 27017: error forwarding port 27017 to pod mongodb-1-zusc8_mongodb, uid : unable to do port forwarding: socat not found.
I0811 13:32:01.772538   35913 portforward.go:247] Handling connection for 27017
E0811 13:32:01.780011   35913 portforward.go:318] an error occurred forwarding 27017 -> 27017: error forwarding port 27017 to pod mongodb-1-zusc8_mongodb, uid : unable to do port forwarding: socat not found.
I0811 13:32:02.284900   35913 portforward.go:247] Handling connection for 27017
E0811 13:32:02.290660   35913 portforward.go:318] an error occurred forwarding 27017 -> 27017: error forwarding port 27017 to pod mongodb-1-zusc8_mongodb, uid : unable to do port forwarding: socat not found.
I0811 13:32:02.791519   35913 portforward.go:247] Handling connection for 27017
E0811 13:32:02.797904   35913 portforward.go:318] an error occurred forwarding 27017 -> 27017: error forwarding port 27017 to pod mongodb-1-zusc8_mongodb, uid : unable to do port forwarding: socat not found.
```

**Comment by rhcarvalho** [comment]
This very likely applies to all other images as well (databases, language stacks).

**Comment by omron93** [comment]
@bparees @hhorak Should this be supported in our images?

**Comment by bparees** [comment]
@omron93 it seems like a reasonable ask to me given openshift's dependency on it for port forwarding (https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/port_forwarding.html#server-operation)

(see @jorgemoralespou?  that's 2.)

**Comment by jorgemoralespou** [comment]
(@bparees I'm starting to get worried.)

**Comment by hhorak** [comment]
I don't see any reason to not do it either.
@jorgemoralespou Reading the docs, but still rather double-checking -- is it just about `socat` package installed in the image and no other changes need to be made?

**Comment by jorgemoralespou** [comment]
That @bparees would answer better. I'm not engineer so I have limited
knowledge.

**Comment by bparees** [comment]
@hhorak i don't actually know myself, port-forwarding was at one point the domain of @ncdc though i'm not sure who it is now.  It seems likely that socat would be the only pre-req though.

**Comment by ncdc** [comment]
`socat` has to live on the node. It does not need to be in individual "app" images.

**Comment by bparees** [comment]
whoops, i totally misread "The supported implementation currently in OpenShift invokes nsenter directly on the node host to enter the pod’s network namespace, then invokes socat to copy data between the stream and the pod’s port. " as implying it was entering the container and invoking socat, not just the network namespace.

Thanks @ncdc 

So @jorgemoralespou this sounds like a more fundamental issue w/ your cluster.  Closing this, you can open an issue in origin if you think it's a bug in cluster up or something.
