### ISSUE TITLE
Rename MONGODB_USERNAME env variable

### ISSUE THREAD

**Issue by jpechane** [sclorg/mongodb-container#18]
Both MySQL and PostgreSQL images have config variable named <database>_USER. MongoDB is thus anomaly and I think the variable should be renamed or support both formats _USER and _USERNAME

**Comment by jhadvig** [comment]
@jpechane thanks for noticing, wil take care of it :+1:

**Comment by jhadvig** [comment]
@mnagy done, I've submitted the PR https://github.com/openshift/mongodb/pull/19

**Comment by jhadvig** [comment]
Done in https://github.com/openshift/mongodb/commit/4dc8b19eeb3cc7ccf40fa11fbefba497ae6a70d8
