### ISSUE TITLE
Add description to the repo

### ISSUE THREAD

**Issue by php-coder** [sclorg/mongodb-container#181]
When I'm opening [repository page](https://github.com/sclorg/mongodb-container) I see a message "No description or website provided." I think that it should be easy to add a description.

**Comment by omron93** [comment]
@php-coder @hhorak @bparees Does any other RHSCL/OpenShift Docker image repository contain similar information?

**Comment by bparees** [comment]
@omron93 no, i think they would all need to be updated if we're going to do this.

**Comment by omron93** [comment]
And what kind of description could be there?

**Comment by hhorak** [comment]
I think a sentence from beginning of the README.md would be sufficient: "Dockerfiles for MongoDB images for OpenShift. Users can choose between RHEL and CentOS based images." There is also possibility to add URL to the project there, do we want to promote some? (maybe some RH containers entry page?)

**Comment by omron93** [comment]
Added description similar to Mariadb contaiener.
"Dockerfiles for MongoDB images for OpenShift and general usage. Users can choose between RHEL and CentOS based images." and URL "https://softwarecollections.org"
