### ISSUE TITLE
Code sharing

### ISSUE THREAD

**Issue by omron93** [sclorg/mongodb-container#194]
Now we have in master replset scripts.
#184 add a new way how to initialize replset and how to manage pods. It does not use much of current code - it works differently (so maybe it's right).
#178 tries to add support to run replication in pure docker environment. The best way how to do this is not to use post-deploy hook for initialization and remove members in `cleanup()`. So this differs from both above mentioned set of scripts! Should this PR bring own set of scripts?

@php-coder @rhcarvalho Any idea how to solve this? I know both PRs are [WIP], but I would like to agree on some "vision" how it could be done. Not to waste time while reworking PRs again and again... or having to make many PRs to bring back sharing of code. Thanks.

(I hope discussing this in separate issue will be more easy and clean than in any of mentioned PRs)

**Comment by rhcarvalho** [comment]
#184 also doesn't remove members from the config.

I think the two ways can share code, they are not incompatible.

And if we factor out our functions better, they would be easier to reuse.

We just feel the pain of working on two different features on the same timeline :)

**Comment by php-coder** [comment]
IMHO we have more serious duplication between 2.4/2.6/3.0/3.2 and dealing with a small duplication between <5 scripts not so important to me. Also it will increase the risk for change because it may breaks more scripts. I like stability and I hate regressions, especially in the unrelated code.

Let's imagine that PetSet goes to beta and now I need to update code for petset. If most of the code will be shared, it is harder to me to modify petset without fear to break standalone mode, for example. I don't want to break it and I don't want to test it also each time I'm changing code for petset.

Does it really a problem for us? Did it cause some problems already? Do it to just follow some principles don't convince me.

IOW I don't feel a pain from the current duplication. Even opposite, I'm happy that I don't need to aware about other pieces of code.

**Comment by praiskup** [comment]
Haven't had a chance to look at those WIP PRs:

@php-coder wrote:

> IMHO we have more serious duplication between 2.4/2.6/3.0/3.2

That's right.  It is just unlucky we haven't been able to deal with this yet, Martin started here sclorg/mysql-container/pull/143.

> and dealing with a small duplication between <5 scripts not so important to me. 

-1, if we are going to ignore that duplication is mistake, we are going to never change this

> Let's imagine that PetSet goes to beta and now I need to update code for petset. If most of the code will be shared, it is harder to me to modify petset without fear to break standalone mode, for example.

Please accept my honest disagreement.  We also don't have multiple kernels, multiple glibc's etc. Maybe that's about making some code a "library" for containers, but code duplication helps nobody at all, except for github code statistics.

Deduplicated code increases code-coverage .. and makes contributors to **think** about self-standing, clean functions with nice API.

I wish we could fix issues once (at one place) and forever, without thinking about what container github repo needs to be changed, yet.

> Does it really a problem for us? Did it cause some problems already?

Duplication code wasted most of the time I spent on reviews against containers...

> Do it to just follow some principles don't convince me.

I for one believe that good programming is set of principles, manners, guidelines.

**Comment by omron93** [comment]
> #184 also doesn't remove members from the config.

@rhcarvalho  Yes. But #178 needs to remove members from config.

> I think the two ways can share code, they are not incompatible.
> And if we factor out our functions better, they would be easier to reuse.

Agree.
"easier to reuse" - why current functions are not good to reuse? Ok, I know it is [WIP]. Do you assume that better new functions that are similar to old one will be merged before #184 get merged (so in the end removed from #184), OR #184 will be merged and old code will have to be changed to use new functions?

---

New functions are not completely different, but there are some conceptual changes.
(from https://github.com/sclorg/mongodb-container/pull/184/#discussion_r82172443 - it should be better to discuss it here)

_In this PR you don't use "complete" functions for one action in mongod (for example mongo_add, mongo_remove,... - they contain everything and are influenced by parameters). Instead of it you save peaces of JavaScript in variables and everytime you want to use it, you have to specify mongo + parameters + from variable assemble the code to evaluate._

_The second approach is more frustrating when using (having to type mongo and parameters every time. On the other hand it is more complex - you only share code but can add whatever you want in each situation._

_What it better and what we decide to use in mongodb scripts (these one and the old one)? (I think it should be consistent) WDYT @rhcarvalho @php-coder ?_*

---

> We just feel the pain of working on two different features on the same timeline :)

IMPOV when the code of current functions would be improved simultaneously, it would be possible. Or at least to do little changes/fixes. Now it seems to me it is not possible to do anything int this repo, because there is an assumption that a lot of things will be different.

To be honest I am completely lost in #184 . I know it is hard to bring new features and to fixe old functions simultaneously.
And also I remember that I wanted to get merged a bunch of new code in one PR:-) But you convinced me, that it is better to split it. And now, I think the result several PR is better than the original PR.

**Comment by omron93** [comment]
@php-coder 

> IMHO we have more serious duplication between 2.4/2.6/3.0/3.2 and dealing with a small duplication between <5 scripts not so important to me. Also it will increase the risk for change because it may breaks more scripts. I like stability and I hate regressions, especially in the unrelated code.
> 
> Let's imagine that PetSet goes to beta and now I need to update code for petset. If most of the code will be shared, it is harder to me to modify petset without fear to break standalone mode, for example. I don't want to break it and I don't want to test it also each time I'm changing code for petset.

IMHO 2.4/2.6/3.0/3.2 differences are not so serious. Everytime I do changes in one versions and then I run a simple script that apply change to other versions. Differences are so small (in mongodb, not sure about other repos) that I don't remember that my changes won't apply automatically to other versions.

---

On the other hand, let't imagine that we found that for example we are not waiting for replication to all members properly. Then it would be hard to figure out in which "set of scripts" it also happen. And then will be hard too to fix all these scripts and ensure that it is fixed!

You think these kind of problem can't appear? IMPOV while fixing bugs in one way how to deploy replset it would be impossible to prevent regressions in other ways how to deploy it.

> IOW I don't feel a pain from the current duplication. Even opposite, I'm happy that I don't need to aware about other pieces of code.

Yes, I agree that is easier NOW. But then in the future it will be much harder.

**Comment by bparees** [comment]
#178 i'm honestly not sure why we are investing effort in.  No one is going to run mongo in "pure docker", if they don't use openshift/k8s they're going to use swarm or something else.

#184 will ultimately supercede the existing replication example/logic at which point duplication can go away when we remove it.

**Comment by omron93** [comment]
> #178 i'm honestly not sure why we are investing effort in. No one is going to run mongo in "pure docker", if they don't use openshift/k8s they're going to use swarm or something else.

@hhorak ?

> #184 will ultimately supercede the existing replication example/logic at which point duplication can go away when we remove it.

@bparees Do we know when? I've heard that 2.4 is going to be EOL, but it is still here :-) So everytime it takes longer time...

Or we won't provide fixes of possible bugs in "old replication" ? (before it will be removed)

**Comment by bparees** [comment]
> @bparees Do we know when? I've heard that 2.4 is going to be EOL, but it is still here :-) So everytime it takes longer time...

2.4 EOLs when the SCL packages EOL.

> Or we won't provide fixes of possible bugs in "old replication" ? (before it will be removed)

that'll probably be the first step.  Anyway the petset replication won't become the "official" replication solution until petstsets are no longer alpha, but even the existing replication solution isn't an official supported thing today.  it's an example.

**Comment by omron93** [comment]
ReplicaSet support can be removed, so this issue is invalid.
