### ISSUE TITLE
Set ulimit to recommended values

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/mongodb-container#202]
Currently the MongoDB image doesn't change the default ulimit values, what is not ideal for production deployments.

https://docs.mongodb.com/manual/reference/ulimit/

**Comment by omron93** [comment]
@hhorak @praiskup @pkubatrh Does setting `limits` also apply to MariaDB/PostgreSQL? Is it somehow handled in RHSCL images?

**Comment by praiskup** [comment]
Ulimits on RHEL/Fedora systems are usually generous enough by default (at least from PostgreSQL POV).

**Comment by praiskup** [comment]
Roughly tried to run ulimit on my box, and it seems that from mongo perspective only the max number of opened file descriptor issue (default is 1024, so far I haven't seen different different default, while mongo suggest to have 64k, which sounds crazy TBH).

**Comment by praiskup** [comment]
Btw., there seems to be soft limit of 4096 simultaneously opened file descriptors per process on my box.  I've seen some weird scenarios (GNU tar archives very deep directory structure) where the default 1024 limit is approached .. but I'm curious whether this is really an issue in case of mongodb and why.

**Comment by omron93** [comment]
Not sure if it good, but it seems that limits are not set in a image, but are related to host machine. So it may differ on every machine...
It is possible to set defaults in docker daemon by using `--default-ulimit` ("If these defaults are not set, ulimit settings will be inherited, if not set on docker run, from the Docker daemon." - https://docs.docker.com/engine/reference/commandline/dockerd/).

In case that other database images are not setting this, using defaults from docker daemon seems enough IMPOV.

**Comment by omron93** [comment]
Although the fix is relatively simple, I would let setting of limits to the user (when invoking `docker run` or centrally to docker daemon). So closing this issue now. It could be fixed when this decision cause any problem to someone.

Proposed fix:
```
diff --git a/3.2/root/usr/bin/run-mongod b/3.2/root/usr/bin/run-mongod
index 2814661..96cca13 100755
--- a/3.2/root/usr/bin/run-mongod
+++ b/3.2/root/usr/bin/run-mongod
@@ -68,4 +68,5 @@ wait_for_mongo_down
 
 # Make sure env variables don't propagate to mongod process.
 unset MONGODB_USER MONGODB_PASSWORD MONGODB_DATABASE MONGODB_ADMIN_PASSWORD
+setup_soft_limits
 exec mongod $mongo_common_args --auth
diff --git a/3.2/root/usr/bin/run-mongod-replication b/3.2/root/usr/bin/run-mongod-replication
index 7c86615..31e1a3c 100755
--- a/3.2/root/usr/bin/run-mongod-replication
+++ b/3.2/root/usr/bin/run-mongod-replication
@@ -69,5 +69,6 @@ ${CONTAINER_SCRIPTS_PATH}/init-replset.sh &
 
 # Make sure env variables don't propagate to mongod process.
 unset MONGODB_USER MONGODB_PASSWORD MONGODB_DATABASE MONGODB_ADMIN_PASSWORD
-mongod ${mongo_common_args} --replSet "${MONGODB_REPLICA_NAME}" &
+(setup_soft_limits;
+mongod ${mongo_common_args} --replSet "${MONGODB_REPLICA_NAME}") &
 wait
diff --git a/3.2/root/usr/share/container-scripts/mongodb/common.sh b/3.2/root/usr/share/container-scripts/mongodb/common.sh
index 4d35a0d..b023d9d 100644
--- a/3.2/root/usr/share/container-scripts/mongodb/common.sh
+++ b/3.2/root/usr/share/container-scripts/mongodb/common.sh
@@ -177,6 +177,14 @@ function setup_default_datadir() {
   fi
 }
 
+# setup_soft_limits sets soft limits to maximum (hard limit)
+function setup_soft_limits() {
+  info "Setting soft limits to maximum"
+  for x in c d e f i l m n q r s t u v x; do
+    ulimit -S${x} $(ulimit -H${x})
+  done
+}
+
 # info prints a message prefixed by date and time.
 function info() {
   printf "=> [%s] %s\n" "$(date +'%a %b %d %T')" "$*"
```
