### ISSUE TITLE
Set cacheSizeGB for 3.2 image

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/mongodb-container#204]
According to the docs:

> If you run mongod in a container (e.g. lxc, cgroups, Docker, etc.) that does not have access to all of the RAM available in a system, you must set storage.wiredTiger.engineConfig.cacheSizeGB to a value less than the amount of RAM available in the container. The exact amount depends on the other processes running in the container.

(https://docs.mongodb.com/manual/faq/storage/#to-what-size-should-i-set-the-wiredtiger-internal-cache)

We currently do not set that configuration option.

**Comment by php-coder** [comment]
Because it uses new config scheme it should be done after #197

**Comment by php-coder** [comment]
BTW, probably, this is also related to https://trello.com/c/tWHmNpY2/895-3-update-mongodb-image-to-autoconfigure-based-on-available-memory-evg33

**Comment by rhcarvalho** [comment]
> Because it uses new config scheme it should be done after #197

This is unrelated to that. It is possible to set this using any of the configuration formats.

From the same docs:

> To adjust the size of the WiredTiger internal cache, see storage.wiredTiger.engineConfig.cacheSizeGB and --wiredTigerCacheSizeGB.

The old configuration format probably takes `wiredTigerCacheSizeGB`.

**Comment by omron93** [comment]
@bparees How it is possible to get maximum amount of RAM in kubernetes/OpenShift?

Postgresql-container uses this group script to get available memory -  https://github.com/sclorg/postgresql-container/blob/master/9.5/root/usr/bin/cgroup-limits, but it is failing for me on F25 because of SElinux.

**Comment by bparees** [comment]
It seems that issue is fixed now, you should be able to read the file again.

**Comment by omron93** [comment]
> It seems that issue is fixed now, you should be able to read the file again.

Thanks, I see. So same script could be probably a way for MongoDB too. I'll prepare PR.
