### ISSUE TITLE
Create StatefulSet deployment for PostgreSQL

### ISSUE THREAD

**Issue by matthyx** [sclorg/mongodb-container#226]
As noted by @bparees there is already a working setup with "pet sets" for mongoDB.
I plan to do the same for PostgreSQL, however it won't solve the non-atomicity of initialize_database discussed in https://github.com/sclorg/postgresql-container/pull/160

**Comment by omron93** [comment]
@matthyx This issue should be probably created for sclorg/postgresql-container

**Comment by matthyx** [comment]
right, sorry
