### ISSUE TITLE
Replication support

### ISSUE THREAD

**Issue by omron93** [sclorg/mongodb-container#228]
Replication using `ReplicaSet` was described in https://github.com/sclorg/mongodb-container/tree/master/2.4/examples/replica . 2.4 is now deprecated, so it is not documented nowhere. All other versions contains ReplicaSet code.

Replication using `StatefulSet` was added only for 3.2.

@bparees Is is possible to remove `ReplicaSet` code and add `StatefulSet` support also for 2.6 and 3.0-upg? Or `ReplicaSet` should still be a way how to deploy replication for <3.2 versions?

**Comment by bparees** [comment]
yes we can do that.
