### ISSUE TITLE
Deploying with glusterfs storage volume

### ISSUE THREAD

**Issue by aliscott** [sclorg/mongodb-container#245]
Has anyone had any experience using this image with a glusterfs storage volume?

From trying it out it works well so far, but was wondering if anyone has seen any issues or might know of potential problems that may arise.

**Comment by omron93** [comment]
@aliscott Whats you experience with mongodb+glusterfs?

**Comment by hhorak** [comment]
mongodb container is not maintained any more in this org. closing.
