### ISSUE TITLE
connecting as admin via gui

### ISSUE THREAD

**Issue by MichealB1969** [sclorg/mongodb-container#272]
Hi,

I'm attempting to connecting to db as default admin user using the admin password which was set during setup.

I am using port forward to enable connecting from local host using Studio 3T but have also tried with Mongo Management Studio and MongoDB Compass but am unable to connect using the admin user.

I can connect as a standard user but need the admin access so i can create collections etc.

I'd appreciate any guidance.

Thanks and happy new year to all :)

Mike

**Comment by MichealB1969** [comment]
Turns out admin user is created in the admin db and not the db specified when setting up in openshift V3

1. port forward using oc port-forward [enter mongo pod name] 27017:27017
2. connect to mongo via cli using mongo -u admin -p [enter password] admin

**Comment by omron93** [comment]
User with `'dbAdminAnyDatabase', 'userAdminAnyDatabase', 'readWriteAnyDatabase', 'clusterAdmin' ` roles can be created only in `admin` database - declared in upstream doc (linked from README). 
But you are right that it is not explicitly written in README itself and it could be.

@MichealB1969 Contribution is really welcomed. Could you create pull request?
