### ISSUE TITLE
Support for journaling

### ISSUE THREAD

**Issue by tux4ever** [sclorg/mongodb-container#284]
Can you describe (example) how it is possible to start the mongodb with journaling support as described under:
https://docs.mongodb.com/v3.4/reference/program/mongod/#cmdoption-mongod-journal

**Comment by omron93** [comment]
Mongodb can be configured by providing custom config file.

Best way is to extend/change default file - https://github.com/sclorg/mongodb-container/blob/master/latest/root/usr/share/container-scripts/mongodb/mongod.conf.template

```bash
$ mkdir mongodb-cfg
$ wget https://raw.githubusercontent.com/sclorg/mongodb-container/master/latest/root/usr/share/container-scripts/mongodb/mongod.conf.template -O mongodb-cfg/mongod.conf

$ #CHANGE mongodb-cfg/mongod.conf (for example addd `journal.commitIntervalMs: 500` in `storage:` section)

$ docker run -ti -e MONGODB_ADMIN_PASSWORD=xxxxx -v $(pwd):/opt/app-root/src:Z centos/mongodb-34-centos7
```

Or you can use [s2i](https://github.com/openshift/source-to-image) to do the image customization - `s2i build $(pwd) centos/mongodb-34-centos7 my-mongodb-centos7` and `my-mongodb-centos7` is then image with your config. Useful especially with OpenShift.

Mongodb config options - https://docs.mongodb.com/v3.4/reference/configuration-options/

**Comment by omron93** [comment]
@tux4ever Do you need any more information/help? Or can I close this issue?

**Comment by tux4ever** [comment]
Thank you very much - the suggested way works fine
