### ISSUE TITLE
Regression introduce with restarting slave pods with PVs

### ISSUE THREAD

**Issue by gabemontero** [sclorg/mongodb-container#291]
See https://github.com/sclorg/mysql-container/pull/215/files#r190365336

Should the example/replica template even have a PVC for the slave?
If so, how do we refactor the reference PR/commit to allow slave pod restart per the openshift/origin extended tests I referenced?

thanks

@openshift/sig-developer-experience fyi

**Comment by bparees** [comment]
@gabemontero i think you opened this against the wrong repo.  should be mysql.

**Comment by gabemontero** [comment]
duh ... yep you are right @bparees

**Comment by gabemontero** [comment]
opened https://github.com/sclorg/mysql-container/issues/226
