### ISSUE TITLE
PVC with replicas

### ISSUE THREAD

**Issue by renuraj18** [sclorg/mongodb-container#306]
I created mongo db cluster with 3 replica set, did any one tried to mount using the PV to persist the data

Please guide

**Comment by lehmeyer** [comment]
this article can be useful. the keyword is "volumeClaimTemplates".

https://kubernetes.io/blog/2017/01/running-mongodb-on-kubernetes-with-statefulsets/

**Comment by hhorak** [comment]
mongodb container is not maintained any more in this org. closing.
