### ISSUE TITLE
Exception in NodeJS app when new version deployed

### ISSUE THREAD

**Issue by BorntraegerMarc** [sclorg/mongodb-container#313]
Hi 👋 

Our openshift app updates our mongodb container to the latest version automatically when a new version is released: https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhscl/mongodb-36-rhel7

After auto updating and re-running the mongodb container the actual container starts fine. However our NodeJS (which is using official nodejs driver & mongoose) app get's an exception: `{"name":"MongoError","message":"Topology was destroyed"}` and can't recover even tough the container is running correctly.

So I have to manually stop the NodeJS app and re-run it. Then it connects fine and stays connected until the next auto update.

Has anyone encountered this problem as well and found a solution?

EDIT: I already tried configuring connection settings in mongoose: `{ keepAlive: 1, reconnectTries: Number.MAX_VALUE }`

**Comment by hhorak** [comment]
the nodejs app uses postgresql now. mongodb container is not maintained any more in this org. closing.
