### ISSUE TITLE
OpenShift InstantiateTemplate is not generating admin password

### ISSUE THREAD

**Issue by rmorrise** [sclorg/mongodb-container#318]
In OpenShift web console on the "Instantiate Template" form, it says that a password will be generated if I don't supply one... but when I instantiate the template, it fails with this error:

Template.template.openshift.io "mongodb-persistent" is invalid: template.parameters[6]: Required value: template.parameters[6]: parameter MONGODB_ADMIN_PASSWORD is required and must be specified

**Comment by hhorak** [comment]
mongodb container is not maintained any more in this org. closing.
