### ISSUE TITLE
Make the _USER and _PASSWORD optional when _ADMIN_PASSWORD is set

### ISSUE THREAD

**Issue by mfojtik** [sclorg/mongodb-container#32]
When the `_ADMIN_PASSWORD` is set (required now in MongoDB) we should make the the _USER and _PASSWORD optional as the user already gets the `admin` account created. When the admin account is created, then we can't force users to also create regular user account as they can use the admin account to create more users.
Also to keep this backward compatible, we can make _USER and _PASSWORD optional for the case that users want to do full bootstrapping.

This was discussed with database guys (@praiskup, @hhorak) already and it makes sense to me as well.

CC @bparees @jhadvig @mnagy @soltysh

**Comment by soltysh** [comment]
:+1: makes sense, if you have an admin user, there's no point in forcing you to create one at start, you can but are not obligated to do so.

**Comment by mnagy** [comment]
What about the database, can it be optional as well?

Also, I think this could also be applicable to MySQL and PostgreSQL images as well.

**Comment by mfojtik** [comment]
@mnagy can you please look at this?

**Comment by bparees** [comment]
@mnagy I suppose DB name can be optional also..if you specify no DB name, we do not initialize any DB for you (which is also going to mean we don't create any admin/user accounts, right?)

@mfojtik what do you think?

**Comment by omron93** [comment]
> I suppose DB name can be optional also..if you specify no DB name, we do not initialize any DB for you (which is also going to mean we don't create any admin/user accounts, right?)

@bparees For example in MongoDB admin user is stored in different database than DB user. So you don't have to create _USER in _DATABASE to have usable admin user.

**Comment by mnagy** [comment]
I think I'll have to look into this post-3.0 for now.
