### ISSUE TITLE
MongoDB images newer than 3.6?

### ISSUE THREAD

**Issue by ewoks** [sclorg/mongodb-container#321]
Is there any specific reason why there are not newer MongoDB images? 
According to [official page](https://www.mongodb.com/try/download/community), currently **v4.4.1** is the latest stable while this repository has 3.6 as the latest

**Comment by pkubatrh** [comment]
Hi @ewoks 
The licensing changed made by mongodb led Red Hat to drop support for new versions of the database, which is why no future versions have been released, nor are planned to be released. As we do not have the mongodb rpms available in RHEL, no images can be built either.

**Comment by ewoks** [comment]
Just found the comment and explanation [here](https://github.com/sclorg/mongodb-container/issues/297#issuecomment-495580010).
Thanks for the confirmation @pkubatrh
