### ISSUE TITLE
Cluster init not working against GA

### ISSUE THREAD

**Issue by smarterclayton** [sclorg/mongodb-container#50]
Did a straight up create - can you replicate?  Want to show this at summit.

```
Mon Jun 22 00:04:04.462 [rsStart] replSet info you may need to run replSetInitiate -- rs.initiate() in the shell -- if that is not already done
=> Waiting for MongoDB service startup  ...
Mon Jun 22 00:04:05.046 [conn1] note: no users configured in admin.system.users, allowing localhost access
=> MongoDB service has started
+ mongo_add
++ mongo_addr
+++ container_addr
++++ cat /var/lib/mongodb/.address
+++ echo -n 172.17.0.70
++ echo -n 172.17.0.70:
++ mongo_primary_member_addr
+++ endpoints
+++ service_name=mongodb
+++ dig mongodb A +search +short
++ local 'current_endpoints=172.17.0.69
172.17.0.70'
+++ echo -n 172.17.0.69 172.17.0.70
+++ cut -d ' ' -f 1
++ local mongo_node=172.17.0.69:
+++ mongo admin -u admin -p 7HsVOJ8NglVa --host 172.17.0.69: --quiet --eval 'print(rs.isMaster().primary);'
exception: connect failed
++ echo -n Mon Jun 22 00:04:05.160 Error: Missing port number in connection string '"172.17.0.69:/admin"' at src/mongo/shell/mongo.js:129
+ echo '=> Adding 172.17.0.70: to Mon Jun 22 00:04:05.160 Error: Missing port number in connection string "172.17.0.69:/admin" at src/mongo/shell/mongo.js:129 ...'
=> Adding 172.17.0.70: to Mon Jun 22 00:04:05.160 Error: Missing port number in connection string "172.17.0.69:/admin" at src/mongo/shell/mongo.js:129 ...
++ mongo_primary_member_addr
+++ endpoints
+++ service_name=mongodb
+++ dig mongodb A +search +short
++ local 'current_endpoints=172.17.0.69
172.17.0.70'
+++ echo -n 172.17.0.69 172.17.0.70
+++ cut -d ' ' -f 1
++ local mongo_node=172.17.0.69:
+++ mongo admin -u admin -p 7HsVOJ8NglVa --host 172.17.0.69: --quiet --eval 'print(rs.isMaster().primary);'
exception: connect failed
++ echo -n Mon Jun 22 00:04:05.234 Error: Missing port number in connection string '"172.17.0.69:/admin"' at src/mongo/shell/mongo.js:129
++ mongo_addr
+++ container_addr
++++ cat /var/lib/mongodb/.address
+++ echo -n 172.17.0.70
++ echo -n 172.17.0.70:
+ mongo admin -u admin -p 7HsVOJ8NglVa --host Mon Jun 22 00:04:05.234 Error: Missing port number in connection string '"172.17.0.69:/admin"' at src/mongo/shell/mongo.js:129 --eval 'rs.add('\''172.17.0.70:'\'');'
MongoDB shell version: 2.4.9
connecting to: Mon:27017/admin
```

**Comment by smarterclayton** [comment]
@jhadvig

**Comment by mfojtik** [comment]
@smarterclayton this one is just obsoleted env var and we fixed this easely... there is another problem with replica setup where the 'service' mongo does not initiate the replica set properly :-( I'm working on this today.

**Comment by jhadvig** [comment]
@smarterclayton there was also a problem with labels in the replica template but @mfojtik already took care of it :+1:

**Comment by mfojtik** [comment]
@smarterclayton also for the future... I would like to know how this cluster example should operate in general.. mainly:

1) Will we support scale up/down or run with static number of replicas?
2) Should we do anything smart regarding to failover?

**Comment by mfojtik** [comment]
@smarterclayton problem should be solved, you have rebuild the image (or wait for the push_image jenkins job to push centos7 image to Hub)

**Comment by smarterclayton** [comment]
I think for now we should probably focus on making the scenario clearly documented here (what we do to solve it), ensure we have the tools support to transition to stateful volumes, and make sure we have good tests that exercise it.  Some of the things we want to make better across other components are represented here - ie, nominal services, an easy way to add volumes, making this easier to understand in the UI, etc

**Comment by mfojtik** [comment]
@smarterclayton there is definitely a room for improvements... a lot of stuff here can be solved without using bash magic... The deployment hooks can solve the problem of 'deregistering' mongo member when it is going down. The pre-deployment hook can solve registration mongo member to cluster, etc...

**Comment by smarterclayton** [comment]
Spending a small amount of time trying to practically use our existing API features is valuable for other reasons - doc, testing, and experience.

**Comment by bparees** [comment]
we have other issues open for improving clustering (and we've probably come a long way since june) so i'm closing this.
