### ISSUE TITLE
Default values for MongoDB configuration

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/mongodb-container#74]
We [set default values](https://github.com/openshift/mongodb/blob/386c1a0d8f4031aabda03464bf18ab5553e2a2ef/2.4/run-mongod.sh#L12-L15) for [`noprealloc`](http://docs.mongodb.org/v2.4/reference/configuration-options/#noprealloc)=`true`, [`smallfiles`](http://docs.mongodb.org/v2.4/reference/configuration-options/#smallfiles)=`true` and [`quiet`](http://docs.mongodb.org/v2.4/reference/configuration-options/#quiet)=`true` which are the opposite of MongoDB's default, and against recommended practice for production.

I'd like to raise a discussion on why we set those values that way.
- noprealloc
  
  > Default: false
  > Set noprealloc = true to disable the preallocation of data files. This will shorten the start up time in some cases, but can cause significant performance penalties during normal operations.
  
  Are we optimizing for short start up times (quick demos) or normal usage?
- smallfiles
  
  > Default: false
  > Set to true to modify MongoDB to use a smaller default data file size. [...]
  > Use the smallfiles setting **if you have a large number of databases that each hold a small quantity of data**. The smallfiles setting can lead mongod to create many files, which may affect performance for larger databases.
  
  Are we assuming somehow that users will be using MongoDB with a small dataset? Right now we  support creating only a single database. I think we should not be assuming anything here, just let MongoDB use its default settings and let users consciously opt for something other than Mongo's default. Again, seems like an optimization for short-lived demos.
- quiet
  
  > Default: false
  > Runs the mongod or mongos instance in a quiet mode that attempts to limit the amount of output. [...]
  > **For production systems this option is not recommended as it may make tracking problems during particular connections much more difficult.**
  
  Why do we suppress logging by default here? Could there be any good reason?

@bparees @mfojtik @jhadvig @mnagy I'm searching for arguments to keep the current default values for those, otherwise I propose changing those to `false` to match Mongo's default. It is possibly too late to remove the env vars, right?

**Comment by bparees** [comment]
we wouldn't want to remove them, then you wouldn't be able to configure it at all...  but we can consider changing the defaults.

**Comment by rhcarvalho** [comment]
@bparees I wouldn't remove them because of backwards-compatibility.
But providing one env var per MongoDB config doesn't scale.
We could rather document how to provide a config file (preferred) or command-line arguments to `mongod`.

**Comment by mfojtik** [comment]
@bparees @rhcarvalho reason why I introduced them is to provide faster container initialization and does not require insane amount of storage/user quota by default just to run a simple MongoDB instance.

**Comment by mfojtik** [comment]
@rhcarvalho pre allocation is a tricky topic in MongoDB. We learned a lesson in OpenShift v2 where creating a MongoDB cartridge (or adding it to your application) took insane amount of time and most likely exhausted your user quota.

**Comment by rhcarvalho** [comment]
> to provide faster container initialization and does not require insane amount of storage/user quota by default just to run a simple MongoDB instance.

@mfojtik I understand the underlying reason, but what is not clear to me is what is the ultimate purpose of the `openshift/mongodb-*` image(s). Are they supposed to be production ready images or not?

Do we expect OpenShift users to use the image we provide or create their own image that is tuned for their application requirements?

**Comment by mfojtik** [comment]
@rhcarvalho I think we should expose that values as environment variables, allowing users to tweak them to suit their environments. By default, I think we should make the MongoDB image fast and use minimum storage.

**Comment by rhcarvalho** [comment]
> I think we should expose that values as environment variables, allowing users to tweak them to suit their environments.

Allowing customization is a valid concern. But we have 3 env vars that default to reversing MongoDB's defaults (surprising anybody coming from a standard MongoDB setup), and no documented way to change other things that are supposed to be tuned in production, e.g., [`oplogSize`](http://docs.mongodb.org/v2.4/reference/configuration-options/#oplogSize) that has direct [implications on replication](http://docs.mongodb.org/v2.4/core/replica-set-oplog/).
That said, I don't think we should then add more env vars, but rather allow users to pass in their `mongodb.conf` and document it.

> I think we should make the MongoDB image fast and use minimum storage.

Again, this sounds like optimizing for quick demos.

---

I would like to converge the focus to why we reverse the defaults in each case.

What I've collected so far from this thread:
- _noprealloc_: we aim to have an image that initially consumes as little storage as possible and that is ready to serve requests as fast as possible.
- _smallfiles_: same as previous.
- _quiet_: no arguments yet.

**Comment by bparees** [comment]
allowing users to provide a config file is a fine idea, no objection to that...but keep in mind the normal way to do that might be to just create your own custom mongodb image layer on top of our image.

and we do want env variables for commonly configured values people can write templates that deploy mongo in specific ways and to provide an easy out of the box experience.  so i would expect us to add more if we get user requests for it.

**Comment by rhcarvalho** [comment]
@bparees I'm fine with all that you're saying. Just still not convinced about our defaults.

**Comment by bparees** [comment]
@rhcarvalho basically our defaults should be optimized for prototyping/rapid-devel.  once you make a decision to go into production you're going to be revisiting all the config settings anyway, so there's not much point in defaulting a couple of them for a production deployment.

it sounds to me like quiet=false is going to be pretty verbose and not useful when you're doing preliminary devel, so it makes sense to me that we'd set it to quiet=true.

**Comment by mnagy** [comment]
Are the benefits of deviating from MongoDB defaults worth the risk that someone runs the image in production with them? I think it's generally safer if you need to explicitly set something in development environment, instead of having to do it for production.

I also think that setting quiet to false also makes more sense when developing as a help when debugging.

**Comment by mfojtik** [comment]
@mnagy users have a way how to tweak this image and change the default we set using `docker build`. Currently it is primarily us (I mean OpenShift) who consume this image. I don't see any problem changing this to the default value if there will be customer request to do so. In meantime, I don't want to make our life more complicated by waiting for MongoDB to allocate several GB just to see the MongoDB works or run a simple example application on it.

**Comment by rhcarvalho** [comment]
I run our image a few times varying the values for the env vars.
Having MONGODB_SMALLFILES=true seems to be the single option that drives down the
startup time... but at a cost if someone ever uses our image for storing any
non-trivial amount of data.

The speedup is understandable, and can be mostly attributed to the size of the
journal. The smallfiles setting reduces the size of each journal file from 1
gigabyte to 128 megabytes.

```
$ docker run --rm -e MONGODB_USER=u -e MONGODB_PASSWORD=p -e MONGODB_DATABASE=db -e MONG
ODB_ADMIN_PASSWORD=secret openshift/mongodb-24-centos7
=> Waiting for container IP address ... 172.17.1.41:27017
=> Waiting for MongoDB service startup  ...
note: noprealloc may hurt performance in many applications
Thu Aug 20 09:47:15.784 [initandlisten] MongoDB starting : pid=24 port=27017 dbpath=/var/lib/mongodb/data 64-bit host=
ebd496a3f452
[...]
Thu Aug 20 09:47:24.175 [initandlisten] waiting for connections on port 27017
```

MONGODB_NOPREALLOC=true, MONGODB_SMALLFILES=true, MONGODB_QUIET=true
took 9s

```
$ docker run --rm -e MONGODB_USER=u -e MONGODB_PASSWORD=p -e MONGODB_DATABASE=db -e MONG
ODB_ADMIN_PASSWORD=secret -e MONGODB_NOPREALLOC=false -e MONGODB_SMALLFILES=false -e MONGODB_QUIET=false openshift/mon
godb-24-centos7
=> Waiting for container IP address ... 172.17.1.42:27017
=> Waiting for MongoDB service startup  ...
warning: remove or comment out this line by starting it with '#', skipping now : noprealloc = false
warning: remove or comment out this line by starting it with '#', skipping now : smallfiles = false
warning: remove or comment out this line by starting it with '#', skipping now : quiet = false
Thu Aug 20 09:49:38.006 [initandlisten] MongoDB starting : pid=25 port=27017 dbpath=/var/lib/mongodb/data 64-bit host=
1f3dddd8249d
[...]
Thu Aug 20 09:50:16.734 [initandlisten] waiting for connections on port 27017
```

MONGODB_NOPREALLOC=false, MONGODB_SMALLFILES=false, MONGODB_QUIET=false
took 38s

```
$ docker run --rm -e MONGODB_USER=u -e MONGODB_PASSWORD=p -e MONGODB_DATABASE=db -e MONG
ODB_ADMIN_PASSWORD=secret -e MONGODB_NOPREALLOC=false -e MONGODB_SMALLFILES=true -e MONGODB_QUIET=false openshift/mong
odb-24-centos7
=> Waiting for container IP address ... 172.17.1.43:27017
=> Waiting for MongoDB service startup  ...
warning: remove or comment out this line by starting it with '#', skipping now : noprealloc = false
warning: remove or comment out this line by starting it with '#', skipping now : quiet = false
Thu Aug 20 11:28:50.722 [initandlisten] MongoDB starting : pid=26 port=27017 dbpath=/var/lib/mongodb/data 64-bit host=
ebeabe16620c
[...]
Thu Aug 20 11:28:59.354 [initandlisten] waiting for connections on port 27017
```

MONGODB_NOPREALLOC=false, MONGODB_SMALLFILES=true, MONGODB_QUIET=false
took 9s

```
$ docker run --rm -e MONGODB_USER=u -e MONGODB_PASSWORD=p -e MONGODB_DATABASE=db -e MONGODB_ADMIN_PASSWORD=secret -e MONGODB_NOPREALLOC=true -e MONGODB_SMALLFILES=false -e MONGODB_QUIET=false openshift/mon$odb-24-centos7
=> Waiting for container IP address ... 172.17.1.44:27017
=> Waiting for MongoDB service startup  ...
warning: remove or comment out this line by starting it with '#', skipping now : smallfiles = false
warning: remove or comment out this line by starting it with '#', skipping now : quiet = false
note: noprealloc may hurt performance in many applications
Thu Aug 20 11:30:30.692 [initandlisten] MongoDB starting : pid=29 port=27017 dbpath=/var/lib/mongodb/data 64-bit host$50823370b3ae
[...]
Thu Aug 20 11:30:59.360 [initandlisten] waiting for connections on port 27017
```

MONGODB_NOPREALLOC=true, MONGODB_SMALLFILES=false, MONGODB_QUIET=false
took 29s

See how a now standard way to initialize the server, disabling journal, makes the
startup super fast:

```
$ docker run --rm -e MONGODB_USER=u -e MONGODB_PASSWORD=p -e MONGODB_DATABASE=db -e MONGODB_ADMIN_PASSWORD=secret -e MONGODB_NOPREALLOC=true -e MONGODB_SMALLFILES=false -e MONGODB_QUIET=false openshift/mongodb-24-centos7 bash -c 'exec mongod --dbpath=/var/lib/mongodb/data --nojournal'
Thu Aug 20 11:58:08.652 [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/var/lib/mongodb/data 64-bit host=44e99d694c14
[...]
Thu Aug 20 11:58:08.675 [initandlisten] waiting for connections on port 27017
```

Took tens of milliseconds...

So if we are optimizing the image for prototyping/rapid-devel, then we should
disable journaling...?!

**Comment by bparees** [comment]
no journal means no recovery?  there's optimizing for performance and there's optimizing for resilience.  removing default resilience goes a bit far for my taste.

and @mnagy i haven't looked at the logs, but i'm assuming from the description that the types of messages "quiet=true" turns off are not the messages you normally need as a developer who is debugging..I assume they are low level replication/traffic/recovery messages.  but i could be wrong, i certainly haven't looked.

At the end of the day, we picked these defaults because they were what we used in v2 and didn't have complaints about them.  absent users coming to us and requesting a different default, i think we should stick with it.  (sorry @rhcarvalho, you don't count as a user :) )

**Comment by rhcarvalho** [comment]
@bparees no journal means you can have inconsistent state of the data files after a crash. Unless the OS/k8s cluster is shutdown abruptly, container shutdowns are clean.

Anyway, I wouldn't like to bake into the image a default value that reverts MongoDB's default. That's my main concern here.

If we think in our templates we need "noprealloc", "smallfiles" and "quiet" because that was the way it worked in OpenShift v2, I would do that either by explicitly specifying those in the templates as env vars or as extra arguments to `mongod`. That has the extra benefit of teaching users how they can set arbitrary MongoDB config options. That also raises the awareness to the fact that we believe those are "better defaults" than those in MongoDB.

We implicitly changing the defaults means that if I want to run a "vanilla" MongoDB server I need to explicitly change those 3 values.

I don't have the experience you @bparees and @mfojtik have with OpenShift v2, but I believe the model we have in v3 is significantly different to allow us to have images that work in a "standard" way, while still having out-of-the-box behavior configured in a "optimized for prototyping/rapid-devel" + v2 compatibility way.

**Comment by mfojtik** [comment]
@rhcarvalho @bparees the complains we were receiving from v2 users about MongoDB was that:

1) It was eating user quotas (even though users have small databases, which was very common)
2) It took very long time to add the cartridge to application as the MongoDB initialization took long time. I can imagine that using NFS volumes this will be even more longer.

**Comment by rhcarvalho** [comment]
@mfojtik I understand that. But why not set that as explicit configuration in our templates rather than baked in defaults in Docker images?

**Comment by bparees** [comment]
templates are a convenience and a stop-gap, i would not assume users will always be deploying mongo via a template.  i'd expect them to deploy it via "oc new-app mongodb --volume=foo" (once new-app supports a volume semantic)

**Comment by bparees** [comment]
(to be clear:  _this_ use of templates is a convenience and a stop-gap)

**Comment by rhcarvalho** [comment]
@wattsteve, since you raised the performance concerns about using network storage vs. local disk (#114), may I bother to ask for your opinion regarding the default config for `mongod`, in particular the ones I mention in this issue, 'noprealloc', 'smallfiles' and 'quiet'?

**Comment by rhcarvalho** [comment]
@bparees apart from re-evaluating our decisions about the default values, what else can we expect to get from this issue?
Old comments indicate we're following the v2 path. Unless we have new knowledge demonstrating that path doesn't apply to containers, this discussion will go nowhere.

That said, is this something worth investigating at some point?

**Comment by bparees** [comment]
Probably not much.  Recent discussions about how disk quota will work for online leaves me even more convinced we have the right defaults here, so as discussed earlier in this thread, unless we start getting complaints from customers about the default settings, i'd like to leave it.  My guess is anyone who cares about those settings is going to have to customize other settings anyway, too.  This way at least we have a set of defaults that works for a use case.
