### ISSUE TITLE
Allow passing extra arguments to mongod

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/mongodb-container#76]
The official [Docker Hub image for MongoDB](https://hub.docker.com/_/mongo/) allows passing arguments to `mongod` via its [entrypoint script](https://github.com/docker-library/mongo/blob/c664ab653154aa4068a46f57ceeacd7c5cda1ae4/2.4/docker-entrypoint.sh).

This feature is useful and users can benefit of it both via `docker run` and within an OpenShift DeploymentConfig (one can specify container args in the pod spec).

**Comment by rhcarvalho** [comment]
@mfojtik @bparees @mnagy PTAL

**Comment by mfojtik** [comment]
@rhcarvalho we should do the same (afaik we already doing that for mysql)

**Comment by bparees** [comment]
+1

**Comment by mfojtik** [comment]
@omron93 PTAL

**Comment by omron93** [comment]
LGTM. I like a way how to configure the image. And I think there should be no problem with this...

I also think it should be good to allow/document users to mount configuration file,... It is a standard way how to configure mongod and when you don't run mongod from kubernetes it easier to use.

However, when we discussed this, I think you said you don't want to allow users to configure everything? Only some option accessible via environment variables...

**Comment by ewoks** [comment]
guess this ticket can be closed, no @omron93 ?

**Comment by hhorak** [comment]
mongodb container is not maintained any more in this org. closing.
