### ISSUE TITLE
No way to specify the oplogSize

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/mongodb-container#77]
We're [hard-coding the `oplogSize` to 64 MB](https://github.com/openshift/mongodb/blob/386c1a0d8f4031aabda03464bf18ab5553e2a2ef/2.4/run-mongod.sh#L69) which greatly limits setting up our replication example for anything past a "it works!" demo.

If an application takes 10 minutes to add 64 MB of data to MongoDB, it means you have a window of only 10 minutes to recover a secondary in case of failures before you have no way to recover it other than a full sync of the database.

I'd prefer to have MongoDB's default of 5% of free space in place, and [be able to specify a different value if necessary](https://github.com/openshift/mongodb/issues/76).

> `oplogSize` specifies a maximum size in megabytes for the replication operation log. `mongod` creates an oplog based on the maximum amount of space available, typically 5% of available disk space. Once the `mongod` has created the oplog for the first time, changing `oplogSize` will not affect the size of the oplog.
> 
> The oplog (operations log) is a special capped collection that keeps a rolling record of all operations that modify the data stored in your databases. MongoDB applies database operations on the primary and then records the operations on the primary’s oplog. The secondary members then copy and apply these operations in an asynchronous process. All replica set members contain a copy of the oplog, allowing them to maintain the current state of the database.
> 
> If an oplog fills up in 24 hours of operations, then secondaries can stop copying entries from the oplog for up to 24 hours without becoming stale.

**Comment by rhcarvalho** [comment]
@mfojtik @bparees @mnagy PTAL

**Comment by mfojtik** [comment]
how do we calculate 5% of free space?

**Comment by rhcarvalho** [comment]
We don't, Mongo does... And we determine the total space with volume specs.

**Comment by bparees** [comment]
how does mongo calculate the free space?  we have a lot of issues w/ metric data that's available within containers reflecting the host, not the container limits.

Also i doubt 5% will be the right value here since i'd anticipate pretty small volumes.  with a 1gig volume, even if entirely empty, you'd be setting the opLog to 50megs.

So while i agree we should make it configurable, i'm not sure i agree that percent of free space is the way to go.  And even if it is, 5% isn't the right default.

**Comment by mfojtik** [comment]
@bparees I think this will be solved now as we will get cgroups mounted to the container. So we can calculate the proper size based on that information.

**Comment by bparees** [comment]
yes, once we move to 1.8(?)

**Comment by hhorak** [comment]
mongodb container is not maintained any more in this org. closing.
