### ISSUE TITLE
Openshift Console Starts Printing same error message on endless loop

### ISSUE THREAD

**Issue by deanpeterson** [sclorg/mongodb-container#84]
I have been trying to get the mongodb replica set example to work for a few days. I have three pods running and I start up the router and add the route to my headless mongodb server.

I add:

mongodb.test.router.default.svc.cluster.local to my /etc/hosts file.

That is a route I added for my mongodb headless service (no ClusterIP). When I attempt to connect to the service using UMONGO with the host mongodb.test.router.default.svc.cluster.local:80, my openshift console forever begins to send this message (it never stops after just one request to connect - it keeps repeating over and over):

E0910 12:54:38.017351 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:38.017371 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:38.892463 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:38.892524 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:38.892774 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:38.892820 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:39.250190 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:39.250232 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:39.250448 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:39.250465 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:41.211770 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:41.211835 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:41.212198 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:41.212243 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:42.628829 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:42.628884 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:42.629189 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:42.629210 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:43.017986 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:43.018050 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:43.018459 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:43.018509 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:43.893363 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:43.893422 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:43.893760 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:43.893813 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:44.250892 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:44.250935 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:44.251186 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:44.251203 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:46.212723 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:46.212769 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:46.213060 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:46.213080 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:47.629693 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:47.629787 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:47.630105 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:47.630124 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:48.019095 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:48.019136 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry
E0910 12:54:48.019446 19243 proxysocket.go:89] Couldn't find an endpoint for default/router:80-tcp: missing service entry
E0910 12:54:48.019493 19243 proxysocket.go:134] Failed to connect to balancer: missing service entry

Why does this not work to connect to mongodb externally? And why does the openshift console start writing that message and never stop?

**Comment by bparees** [comment]
If this is still an issue, I suggest you reopen it against the origin repo since it sounds more like a fundamental routing/service issue/question than something specific to the mongo image defined here.
