### ISSUE TITLE
At what point does oc env MONGODB_SERVICE_HOST get populated?

### ISSUE THREAD

**Issue by alberttwong** [sclorg/mongodb-container#92]
I have a question.  The code knows to pull the correct IP for mongodb using $MONGODB_SERVICE_HOST.  When does this variable get created and populated?   When "oc new-app mongodb" get executed?   If so, I tried to do a search across this project (returned 0 results) and couldn't find the spot that defines it.

**Comment by bparees** [comment]
that value is automatically defined/injected by openshift/k8s when you have a service named "mongodb" defined in your namespace.
