### ISSUE TITLE
Test DATADIR permissions and fail cleanly

### ISSUE THREAD

**Issue by markllama** [sclorg/mongodb-container#99]
When running this image in Kubernetes 1.1.0, the USER clause and the ownership/permissions imposed on the volume _/var/lib/mongodb/data_ by kubernetes are incompatible. If we check the permissions before starting the daemon we can provide a clear error message and avoid waiting/thrashing.
### Process and File Ownership/Permissions

```
process: uid=184(mongodb) gid=998(mongodb) groups=998(mongodb)
directory: drwxr-x---. 2 root root 6 Oct 29 13:49 /var/lib/mongodb/data
```

This causes the intialization to fail when creating a lock file.  The script proceeds to wait for the DB to become available and eventually times out.  The actual error is buried in the logs.
### Log Example

```
...
Thu Oct 29 13:57:59.288 [initandlisten] exception in initAndListen std::exception: boost::filesystem::status: Permission denied: "/var/lib/mongodb/data/mongod.lock", terminating
Thu Oct 29 13:57:59.288 dbexit: 
Thu Oct 29 13:57:59.288 [initandlisten] shutdown: going to close listening sockets...
...
Thu Oct 29 13:57:59.289 dbexit: really exiting now
 => Waiting for MongoDB service startup ...
=> Waiting for MongoDB service startup  ...
=> Waiting for MongoDB service startup  ...
... 
=> Waiting for MongoDB service startup  ...
=> Giving up: Failed to start MongoDB service!
```

**NOTE:** In OpenShift this is not observed because OpenShift imposes a high numbered UID and GID 0.  The effect is that the mongodb process can write to the volume even though it has _root:root_ ownership.

Upstream changes to Kubernetes, allowing Security Contexts to impose non-root groups on both processes and filesystems will allow this container to run as expected.  It still would be nice to check and report if the DATADIR is not writable.

**Comment by rhcarvalho** [comment]
FTR, #190 added a similar check to the keyfile creation flow. Unfortunately, that only applies the case where we do replication (and not the standalone use case).
